version: '3.8'

services:
  # Your Application Service
  app:
    #build: .
    image: ghcr.io/edwinteo96/libsystem:latest
    ports:
      - "${APP_PORT:-8080}:8080"  # Configurable port
    environment:
      - DB_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs  # For persistent logs (optional)

  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-library}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-foo123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #- ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Optional initial data
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-library}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:  # Persistent database storage

# (Optional) For local development with test data
# networks:
#   library-net:
#     driver: bridge